{
  "formatVersion": "1.1",
  "component": {
    "group": "com.movewithmovr.movr_module",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 16032247,
          "sha512": "90ee66d287c62002a4e3c1090483d4b3726e2a71a77093769d75672b8d260d7df25c0ec38ee7bf2cca033e42f8b86845d3426c07739323296be609c18b522a12",
          "sha256": "2c1bb7c52ff1d316a7efc8504940186ae11a537b9b1ef7aa28117d5cc5b3206c",
          "sha1": "cfb0bb92f6a01c3428f8055d316568f028b42161",
          "md5": "8421bd4c8311ceecab0018b851bb27b2"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 16032247,
          "sha512": "90ee66d287c62002a4e3c1090483d4b3726e2a71a77093769d75672b8d260d7df25c0ec38ee7bf2cca033e42f8b86845d3426c07739323296be609c18b522a12",
          "sha256": "2c1bb7c52ff1d316a7efc8504940186ae11a537b9b1ef7aa28117d5cc5b3206c",
          "sha1": "cfb0bb92f6a01c3428f8055d316568f028b42161",
          "md5": "8421bd4c8311ceecab0018b851bb27b2"
        }
      ]
    }
  ]
}
