{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_debug-1.0.aar",
          "url": "sqflite_debug-1.0.aar",
          "size": 47359,
          "sha512": "e80fb8b94abcca695612c564637129fe2fbc4f571822080125ace122618947cd3a2713963e7d622dd352d21ccc6552884436773ec3800093393be100764f4135",
          "sha256": "71cfebf0a6dadd8175d4460dbf4bff9b20ca10b0f25ce7de563c077ea3af8051",
          "sha1": "80ca0cb895b372be188b2f6e21f84325126c3ee5",
          "md5": "9db26ac68cbf35e74517ab30d9bda695"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_debug-1.0.aar",
          "url": "sqflite_debug-1.0.aar",
          "size": 47359,
          "sha512": "e80fb8b94abcca695612c564637129fe2fbc4f571822080125ace122618947cd3a2713963e7d622dd352d21ccc6552884436773ec3800093393be100764f4135",
          "sha256": "71cfebf0a6dadd8175d4460dbf4bff9b20ca10b0f25ce7de563c077ea3af8051",
          "sha1": "80ca0cb895b372be188b2f6e21f84325126c3ee5",
          "md5": "9db26ac68cbf35e74517ab30d9bda695"
        }
      ]
    }
  ]
}
