{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-1.0.aar",
          "url": "sqflite_release-1.0.aar",
          "size": 45198,
          "sha512": "2dcdedd77c35b4bf19d87a9a9d31eada783b4afc194d398c8f0eb97e05994156e87e16ccffecbb7485c144cab059b680161e4b0a0c0d866ecf839250775e621b",
          "sha256": "b7dcaed54b60f60053a49c2e9bacf043fe930a2e4842107025b609fd6177f951",
          "sha1": "02c1300df2edd704648da711d994cc58799a3e64",
          "md5": "702c72072c3df4d08b80d3051f3f5141"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-1.0.aar",
          "url": "sqflite_release-1.0.aar",
          "size": 45198,
          "sha512": "2dcdedd77c35b4bf19d87a9a9d31eada783b4afc194d398c8f0eb97e05994156e87e16ccffecbb7485c144cab059b680161e4b0a0c0d866ecf839250775e621b",
          "sha256": "b7dcaed54b60f60053a49c2e9bacf043fe930a2e4842107025b609fd6177f951",
          "sha1": "02c1300df2edd704648da711d994cc58799a3e64",
          "md5": "702c72072c3df4d08b80d3051f3f5141"
        }
      ]
    }
  ]
}
