{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 12511,
          "sha512": "fcc074fdfb5eda429f5d32914a6de714e4b38702e08ef3bea4e1125bd1dd9fce552d400f33dfd776606ef8ef6bf3778275b7c434cef7c621d789967701d853ac",
          "sha256": "6a75e6f5d132a0d37836c1253ec819c34dcd96700c111f028e34c45ebca781be",
          "sha1": "a72ef5dd5c878da8ff40b58cf4303eddfe2858c2",
          "md5": "6a02b094af051a9eb247fb00a777ca16"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 12511,
          "sha512": "fcc074fdfb5eda429f5d32914a6de714e4b38702e08ef3bea4e1125bd1dd9fce552d400f33dfd776606ef8ef6bf3778275b7c434cef7c621d789967701d853ac",
          "sha256": "6a75e6f5d132a0d37836c1253ec819c34dcd96700c111f028e34c45ebca781be",
          "sha1": "a72ef5dd5c878da8ff40b58cf4303eddfe2858c2",
          "md5": "6a02b094af051a9eb247fb00a777ca16"
        }
      ]
    }
  ]
}
