{
  "formatVersion": "1.1",
  "component": {
    "group": "com.movewithmovr.movr_module",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-6e2ea58a5ccbefcfadc2d4b7b8045fc6c20ab812"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-6e2ea58a5ccbefcfadc2d4b7b8045fc6c20ab812"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-6e2ea58a5ccbefcfadc2d4b7b8045fc6c20ab812"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-6e2ea58a5ccbefcfadc2d4b7b8045fc6c20ab812"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 14419236,
          "sha512": "1583d92026150c4e10f8cf959dd1429b7721745b95c0f1601c48bd5996614fb186082037fb07d6bdb61c01f6f146727c1a5116aebb5811659300da905d209121",
          "sha256": "f9efcdb4c84404a3acf2cd6192d401c3e10291d7dadd4bf488ef065c87496612",
          "sha1": "59483fce53409e857318aadbec126cd1f9ccb66e",
          "md5": "92cbeb108859e7170f821b5885cdb8e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-6e2ea58a5ccbefcfadc2d4b7b8045fc6c20ab812"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-6e2ea58a5ccbefcfadc2d4b7b8045fc6c20ab812"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-6e2ea58a5ccbefcfadc2d4b7b8045fc6c20ab812"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-6e2ea58a5ccbefcfadc2d4b7b8045fc6c20ab812"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 14419236,
          "sha512": "1583d92026150c4e10f8cf959dd1429b7721745b95c0f1601c48bd5996614fb186082037fb07d6bdb61c01f6f146727c1a5116aebb5811659300da905d209121",
          "sha256": "f9efcdb4c84404a3acf2cd6192d401c3e10291d7dadd4bf488ef065c87496612",
          "sha1": "59483fce53409e857318aadbec126cd1f9ccb66e",
          "md5": "92cbeb108859e7170f821b5885cdb8e0"
        }
      ]
    }
  ]
}
