{
  "formatVersion": "1.1",
  "component": {
    "group": "com.movewithmovr.movr_module",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 12958300,
          "sha512": "a60e134a326ef195b9d5070d372a1c01e64ddf367d4c30c223222bcfce17bd6d5ceaac0988a96a09ef0a0ca155516bb5014765f9b744479e91309fd73e6b7be0",
          "sha256": "db7e467b92d9bbbb8ab512b5e4cb37daa50ea91bde79c7643edbc368994866d1",
          "sha1": "5e90c7bf130435cac58ce54c18077af9d1a9b186",
          "md5": "4b18d0a98de97404ea3a4df9c797dd8d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 12958300,
          "sha512": "a60e134a326ef195b9d5070d372a1c01e64ddf367d4c30c223222bcfce17bd6d5ceaac0988a96a09ef0a0ca155516bb5014765f9b744479e91309fd73e6b7be0",
          "sha256": "db7e467b92d9bbbb8ab512b5e4cb37daa50ea91bde79c7643edbc368994866d1",
          "sha1": "5e90c7bf130435cac58ce54c18077af9d1a9b186",
          "md5": "4b18d0a98de97404ea3a4df9c797dd8d"
        }
      ]
    }
  ]
}
