{
  "formatVersion": "1.1",
  "component": {
    "group": "com.movewithmovr.movr_module",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 23427954,
          "sha512": "7f2a4ab46e92f9f7961aeb938d56af99ba8430007a21e2fb9a7177a2041ec04499027d116fbc31f9eb3f1e1a223695f77d2299a7ed50fc0133283fdd872e8151",
          "sha256": "b942b0eccd5922394f9d72c6828f4f55af89f0dffd8ab9a8de065383cbc1d366",
          "sha1": "b13691f837b8fdd47090f234eba9880fc3c7dd71",
          "md5": "34938412e00d512420aaf4a6e4980dc6"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 23427954,
          "sha512": "7f2a4ab46e92f9f7961aeb938d56af99ba8430007a21e2fb9a7177a2041ec04499027d116fbc31f9eb3f1e1a223695f77d2299a7ed50fc0133283fdd872e8151",
          "sha256": "b942b0eccd5922394f9d72c6828f4f55af89f0dffd8ab9a8de065383cbc1d366",
          "sha1": "b13691f837b8fdd47090f234eba9880fc3c7dd71",
          "md5": "34938412e00d512420aaf4a6e4980dc6"
        }
      ]
    }
  ]
}
